services:
  - type: web
    name: openanimal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m openanimal.webapp
    envVars:
      - key: OPENANIMAL_TICK_INTERVAL_MIN
        value: "60"
      - key: OPENANIMAL_TICK_INTERVAL_MAX
        value: "120"
      - key: OPENANIMAL_TICKS_PER_INTERVAL
        value: "1"
